### ISSUE TITLE
Segmentation Fault when simulating WCE

### ISSUE THREAD

**Issue by ntanmayee** [gymreklab/chips#65]
I'm getting a Segmentation Fault when I try to simulate WCE (`bed` works fine). 

```
[chips-2.4]ProgressMeter: Running simulate with the following model
K: 6.22944 Theta: 35.8361
f: 6.11061e-05
s: 0.164201
pcr rate: 1
Current random seed: 3597572743
[chips-2.4]ProgressMeter: Loading the input ChIP-seq peak file (and BAM file if given)
*** Error in `chips': free(): invalid size: 0x00007ffed191c2d0 ***
Segmentation fault (core dumped)
```

This is the command that I used -- 

```
chips simreads -f hg19.fa -t wce -o wce_test --scale-outliers -c 7 --model h3k27me3_sim.json --region chr21:1-48000000
```

Any help would be much appreciated!

**Comment by Pandaman-Ryan** [comment]
Hi @ntanmayee 

Thank you for your question. However, I was unable to get the same result from my end.

I used:
chips simreads -f hg19.fa -t wce -o wce_test --scale-outliers -c 7 --model test.json --region chr21:1-4800000

(BTW, in this case, since there is no peak file specified, -c is not necessary)

Here, test.json is the same as the README example:
{
    "frag": {
        "k": 15.783836364746094,
        "theta": 14.306901931762695
    },  
    "pcr_rate": 0.7234475612640381,
    "pulldown": {
        "f": 0.15454448759555817,
        "s": 0.8646870851516724
    }   
}

Could you please share the json file you used in this example?

Many thanks,
-An
